### ISSUE TITLE
Telegram bot trunks GPT response.

### ISSUE THREAD

**Issue by ainochkin** [ViktorAllayarov/ChatGPT_telegram_bot#1]
Viktor,
Your bot, and demo bot also, looks very nice.
But if response for question is a bit longer, telegram bot trunks it. It would be good to send full GPT response in several telegram messages.

Thanks.

**Comment by ViktorAllayarov** [comment]
Hi, i add commit with code that check length response text, and then send several messages if length > 4090. Telegram trunk message that longer than 4096 chars, but i cant to get response with text more than 4096 chars, and so cant to check the code all options=)) So i close commit as complete, until the next similar problem=)
