### ISSUE TITLE
after updating with key verification error

### ISSUE THREAD

**Issue by Stranik22** [ViktorAllayarov/ChatGPT_telegram_bot#4]
After updating with key verification error

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    env["API_KEY_CHATGPT"],
KeyError: 'API_KEY_CHATGPT'

Maybe I'm doing something wrong...

**Comment by Stranik22** [comment]
Sorry, it was my mistake, I figured it out already. The code is correct

**Comment by PolinaSpesivtseva** [comment]
I have the same problem! Can you tell me what is my mistake, please??
